### ISSUE TITLE
"SELECT something AS ..." does not work in the child class

### ISSUE THREAD

**Issue by ealymbaev** [hzamani/active_record-acts_as#21]
I have the following structure:

`class Listing < ActiveRecord::Base`
`  actable`
`end`

`class Job < ActiveRecord::Base`
`  acts_as :listing`
`end`

When I run the query like:

`Listing.select('listings.*, some_calculations AS distance').first.distance`

It returns the correct "distance" value.

BUT when I run the query:

`Job.select('jobs.*, some_calculations AS distance').first.distance`

the "distance" is undefined. The attributes don't contain "distance" field.

Need help. Thanks.

**Comment by mintuhouse** [comment]
+1
Does anyone know how to achieve above?

**Comment by mintuhouse** [comment]
Use
Job.unscoped to remove the default_scope :eager_load(:listing)

**Comment by nagliyvred** [comment]
+1 
For me, removing default scope is not the greatest option. Is there a proper way to resolve this?

**Comment by tombowo** [comment]
+1

Using 'joins' (instead of the 'includes' in 1.0.8 or 'eager_load' in 1.0.7) as the association method might help: 
https://github.com/hzamani/active_record-acts_as/pull/72
