### ISSUE TITLE
Saving a acts_as record does not callback .touch on actable relation

### ISSUE THREAD

**Issue by dja** [hzamani/active_record-acts_as#41]
If I have a model Product.rb with related associations like Brand.rb, I want to make sure Brand gets updated when Product gets updated. To do this, I'm using touch: true on the Product > Brand association. If I have Pen.rb that acts_as Product, and Pen gets saved, Product does not update Brand.

Code examples:

``` ruby
class Brand < ActiveRecord::Base
    has_many :products
end
```

``` ruby
class Product < ActiveRecord::Base
    actable
    belongs_to :brand, touch: true
end
```

``` ruby
class Pen < ActiveRecord::Base
    acts_as :product
end
```

**Comment by extrajordanary** [comment]
Would also like this feature.
