### ISSUE TITLE
"Where" changes behavior

### ISSUE THREAD

**Issue by hut8** [hzamani/active_record-acts_as#53]
Hello there. Thanks for this gem! It's saved me lots of time. Please forgive me if this is a duplicate issue; I searched the existing issues and couldn't find something like this.

Normally when I have a `product` that `belongs_to` a `store`, I can search for products in a store like this:

``` ruby
@some_store = Store.find(5)
# ... some code
@products = Product.where(store: @some_store)
```

It seems like in this case, if you have a `Pen` that acts as a `Product`, then this won't work:

``` ruby
@pens = Pen.where(store: @some_store)
```

it will complain about an undefined column, `products.store`. So instead I'm doing this:

``` ruby
@pens = Pen.where(store_id: @some_store.id)
```

It's not a big deal, but it's not what I expected and took me a couple minutes to realize that your gem changes this behavior. What do you think?

**Comment by manuelmeurer** [comment]
This should work with the latest version of this gem.
