### ISSUE TITLE
rails_admin compatability

### ISSUE THREAD

**Issue by hut8** [hzamani/active_record-acts_as#54]
I posted this in https://github.com/sferik/rails_admin, but was wondering if anyone from this project had experience with using `active_record-acts_as` with `rails_admin`. Adding a new `Book` or `Pen` (either of which act as a `Product`) does not insert something into the `products` table when using `rails_admin`. I've looked for some sort of workaround, but no luck. Thanks for any assistance anyone can provide.

https://github.com/sferik/rails_admin/issues/2463

**Comment by adrienbourgeois** [comment]
Hi @hut8 , the way I got that working is by using reform and this gem: https://github.com/bolshakov/activeadmin-reform which allows you to use reform with active_admin. It worked out well for me as I was already using reform in my project.

**Comment by manuelmeurer** [comment]
Closing this for now, feel free to open issues or PRs on how to improve compatibility with rails_admin.
