### ISSUE TITLE
NameError: Undefined local variable or method actable

### ISSUE THREAD

**Issue by Quynhnganguyen** [hzamani/active_record-acts_as#69]
Hello,
I creates a simulate multiple table inheritance, Categories (Clothing, Car, Shoes, ...)

_categorie.rb_

```
class Categorie < ActiveRecord::Base
    actable
    validates_presence_of :nom_categorie
    has_many :annonces
end
```

_clothing.rb_

```
class Clothing < ActiveRecord::Base
    acts_as :categorie
end
```

And after, when I try to getting all the categories in annonce controller, 

```
@categories = Categorie.all
```

I across this error. 

How can I fix it?

**Comment by so77id** [comment]
i have same error :(

**Comment by manuelmeurer** [comment]
I'm pretty sure you just haven't loaded the gem properly. Did you add `gem "active_record-acts_as"` to your `Gemfile`, run `bundle install` and restart the server?

**Comment by so77id** [comment]
It was very strange what happened, the gem was well installed but nothing worked, until I reboot the computer and everything worked as it should be :(

Shit happens

**Comment by hugomaiavieira** [comment]
@so77id you may not have restarted [spring](https://github.com/rails/spring) server, if you use it.

**Comment by adiakritos** [comment]
In my case there is no server running while I run these tests. I'm trying to this this gem within a rails engine. Any thoughts?
