### ISSUE TITLE
Is there a way I can filter Parent objects with children attribute?

### ISSUE THREAD

**Issue by icemall** [hzamani/active_record-acts_as#83]
Hello there!

Would you please let me know if there's a way of filtering Parent objects depending on children attribute?

For example, 

`Request.where(number: 2) `

while `number` attribute is in product_requests table.

**Comment by manuelmeurer** [comment]
This is the most straightforward way I can think of: `Request.where(actable: ProductRequest.where(number: 2))`

**Comment by manuelmeurer** [comment]
You can now use `ProductRequest.where(number: 2).actables` (since v2.1.0).
