### ISSUE TITLE
Can't use specific or actable in Parent Object until record is saved

### ISSUE THREAD

**Issue by brunzino** [hzamani/active_record-acts_as#85]
It appears references to the child object aren't available until the record is saved. This makes it difficult to work with new objects, and means tests need to write to the database instead of just build. Is this expected behavior? Is there a workaround?

```ruby
class Report < ActiveRecord::Base
	actable
	def actable_is_nil?
		return actable.nil? 
	end
end



class DailyReport
	acts_as :report 
end
```

```
> r = DailyReport.new
> r.actable_is_nil?
	=> true
> r.specific
	=> nil
> r.save
> r.actable_is_nil?
	=> false

```

**Comment by manuelmeurer** [comment]
Thanks for reporting this, @brunzino! Try v2.0.7! 😄
