### ISSUE TITLE
not touching child

### ISSUE THREAD

**Issue by abacha** [hzamani/active_record-acts_as#87]
When I touch the object it only affects the super not the object itself

**Comment by manuelmeurer** [comment]
Could you give an example of what you are trying to do?
When you call `submodel.touch(arg)` with `arg` being a datetime attribute of the submodel, it should be updated. Does that not happen for you?

Please note that the canonical repo for this gem is now https://github.com/krautcomputing/active_record-acts_as
Could you reopen the issue there with a code example, or better yet a failing spec?
Thanks!
