### ISSUE TITLE
Rails 5.1 warnings

### ISSUE THREAD

**Issue by jefree** [hzamani/active_record-acts_as#90]
After update to rails 5.1 in my project, i'm getting a lot of warnings that i tracked down to this gem:

> DEPRECATION WARNING: The behavior of `changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_changes?` instead.

> DEPRECATION WARNING: The behavior of `changed_attributes` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_changes.transform_values(&:first)` instead.

I tried to replace `changed?` by `saved_changes?` but some tests fails and it says `saved_changes?` method doesn't exist. #89

**Comment by manuelmeurer** [comment]
Well, I could remove the deprecation warnings but one spec actually fails.
Will investigate further in the next days. Suggestions welcome! 😸

**Comment by 6temes** [comment]
Is there any update on this?

**Comment by manuelmeurer** [comment]
@6temes Do you still see the warnings when you use https://github.com/krautcomputing/active_record-acts_as master?

**Comment by 6temes** [comment]
I configured the master branch in my Gemfile and I don't have any warning. 🎉 

Would it be possible to create a new release with the current master?

Thanks!

**Comment by manuelmeurer** [comment]
I wanted to find out what causes one spec to fail with Rails 5.1 before releasing a new version: https://travis-ci.org/krautcomputing/active_record-acts_as
Just didn't have time yet... any help is appreciated of course! 😄
