### ISSUE TITLE
It doesn't support with rails 5.1

### ISSUE THREAD

**Issue by eashward** [hzamani/active_record-acts_as#92]
I am getting this error
ActiveRecord::HasManyThroughOrderError: Cannot have a has_many :through association 'Store#fulfillment' which goes through 'Store#service' before the through association is defined.

I have this in models
class Store < ApplicationRecord
  acts_as :service
  has_one :fulfillment, class_name: 'Billing::Fulfillment', through: :service, dependent: :destroy
end

class Service < ApplicationRecord
actable
end
the has_one association (has_one :store is build by gem itself), I don't know what I am doing wrong. It works fine with rails 4.2 this issue is occurring when I Upgrade to rails 5.1

**Comment by eashward** [comment]
https://github.com/krautcomputing/active_record-acts_as/issues/11

**Comment by abacha** [comment]
why this was closed? what was the solution? i`m having this issue with rails 5.1
